### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by j2l** [neelsomani/literature-server#19]
Hello,
This server seems great!
I'm trying to make it in docker and hit an error with npm and some modules:
```
root@a4af4bab008e:/app# npm i
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/is
sues/3142
loadDep:fsevents -> resol / |#####################------------------------------------------------------|
WARN engine fsevents@2.1.2: wanted: {"node":"^8.16.0 || ^10.6.0 || >=11.0.0"} (current: {"node":"8.10.0","loadDep:eslint-utils -> g | |#####################------------------------------------------------------|
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! Linux 5.3.0-7648-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
```
I know it's npm at fault but could you please let me know if you can successfully build a working docker image?

I'd like to build another card game I develop and train a neural network.

**Comment by neelsomani** [comment]
Hi @j2l, sure thing. Here's a `Dockerfile` and a `start.sh` script.
[Archive.zip](https://github.com/neelsomani/literature-server/files/4807542/Archive.zip)

`Dockerfile`:
```
FROM nikolaik/python-nodejs:python3.6-nodejs12

RUN cd /home/ && git clone https://github.com/neelsomani/literature-server.git

RUN cd /home/literature-server && pip3 install -r requirements.txt && npm install

RUN curl https://cli-assets.heroku.com/install.sh | sh

ADD start.sh /
RUN chmod +x /start.sh

EXPOSE 5000

CMD ["/start.sh"]
```

`start.sh`:
```
#!/bin/bash

cd /home/literature-server
npm run build
DEBUG=true heroku local
```

Just download the files and build the image with something like `docker build -t neelsomani/literature:v1 .`. Then you can start a new container with `docker run -it -p 127.0.0.1:5000:5000 neelsomani/literature:v1`, and the server will be running at http://localhost:5000.

Could you link me to whatever you end up building? Curious to see what you make, maybe I can link back to your repo!

**Comment by j2l** [comment]
Sorry for the late reply. Was busy.
Thank you very much! Very detailed instructions
`ADD start.sh /` and following instructions didn't go through. Maybe because I was using Portainer and not the terminal.

**Comment by neelsomani** [comment]
Yes, that probably wouldn't work on Portainer since it would need to know where the script is located. Closing this issue since that's a solved problem but let me know if anything else comes up!
